[book]
authors = ["Viktor Ageyev"]
language = "ru"
multilingual = false
src = "src"
title = "Сознание и существование. Библейская интерпретация квантовой механики"

git-repository-url = "https://github.com/ageyev/ageyev.github.io/tree/master/physics/ru.consciousness.and.existence"
git-repository-icon = "fa-github"

[output.html.search]
enable = false

